####
# GitLab CI
####

# Image
image: ubuntu:24.04

# Stages
stages:
  - build

variables:
  CCACHE_DIR: "$CI_PROJECT_DIR/cache/ccache"
  CCACHE_BASEDIR: "$CI_PROJECT_DIR"
  CCACHE_COMPRESS: "true"

cache:
  key: "ccache-$CI_COMMIT_REF_SLUG"
  paths:
    - "$CI_PROJECT_DIR/cache"

# Build
Assemble:
  stage: build
  artifacts:
    paths:
    - dist/
  before_script:
  # Packages
  - apt-get update && apt-get install -y build-essential git libssl-dev libgmp3-dev libbz2-dev zlib1g-dev libcurl4-openssl-dev curl cmake ccache
  script:
  - cd $CI_PROJECT_DIR
  - gcc --version
  - cmake --version
  - export PATH="/usr/lib/ccache:$PATH"
  - export CC="ccache gcc"
  - export CXX="ccache g++"
  - export CMAKE_CC_COMPILER_LAUNCHER="ccache"
  - export CMAKE_CXX_COMPILER_LAUNCHER="ccache"
  - mkdir -p jass cache/ccache cache/curl dist/bin-static dist/bin-shared
  - curl --remote-time --time-cond cache/curl/Blizzard.j --output cache/curl/Blizzard.j "https://raw.githubusercontent.com/lep/jassdoc/master/Blizzard.j" || true
  - curl --remote-time --time-cond cache/curl/common.j --output cache/curl/common.j "https://raw.githubusercontent.com/lep/jassdoc/master/common.j" || true
  - cp cache/curl/Blizzard.j jass/Blizzard.j
  - cp cache/curl/common.j jass/common.j
  # BNCSUtil (dynamic, .so)
  - cd $CI_PROJECT_DIR
  - cd deps/bncsutil/src/bncsutil
  - export BNCSUTIL_SHARED_LIB=1
  - make && make install
  - unset BNCSUTIL_SHARED_LIB
  - cd $CI_PROJECT_DIR
  ## Shared library
  - cp /usr/lib/libbncsutil.so /usr/local/lib
  - cp /usr/lib/libbncsutil.so* dist/bin-shared
  ## Header files
  ### - cp -R /usr/include/bncsutil dist/include
  # StormLib (shared, .so)
  - cd $CI_PROJECT_DIR
  - cd deps/StormLib
  #- sed -i -e 's/option(BUILD_SHARED_LIBS "Compile shared libraries" OFF)/option(BUILD_SHARED_LIBS "Compile shared libraries" ON)/g' CMakeLists.txt
  - rm -rf build && mkdir -p build
  - cd build && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=1 ..
  - make && make install
  - cd $CI_PROJECT_DIR
  ## Shared library
  ### Already at /usr/local/lib
  ### - cp /usr/local/lib/libstorm.so /usr/local/lib
  - cp /usr/local/lib/libstorm.so* dist/bin-shared
  ## Header files
  ### - cp /usr/local/include/StormLib.h dist/include/stormlib
  ### - cp /usr/local/include/StormPort.h dist/include/stormlib
  # pjass (dynamic, .so)
  #- cd $CI_PROJECT_DIR
  #- cd deps/pjass
  #- export PJASS_TYPE=shared
  #- make && make install
  #- unset PJASS_TYPE
  #- cd $CI_PROJECT_DIR
  ## Shared library
  #- cp /usr/lib/libpjass.so /usr/local/lib
  #- cp /usr/lib/libpjass.so* dist/bin-shared
  # MiniUPNP (shared, .so)
  - cd $CI_PROJECT_DIR
  - cd deps/miniupnpc
  - make && make install
  - cd $CI_PROJECT_DIR
  ## Shared library
  - cp /usr/lib/libminiupnpc.so /usr/local/lib
  - cp /usr/lib/libminiupnpc.so* dist/bin-shared
  # CPR (shared, .so)
  #- cp -r --preserve=all cpr-src/ cpr-src-cached/ || true
  #- rm -rf cpr-src
  - git clone https://github.com/libcpr/cpr.git cpr-src --depth 1
  #- cp -r --preserve=all cpr-src-cached/* cpr-src/ || true
  #- rm -rf cpr-src-cached || true
  - cd cpr-src && mkdir -p build && cd build
  - cmake .. -DCPR_USE_SYSTEM_CURL=ON -DBUILD_SHARED_LIBS=ON
  - cmake --build . --parallel
  - cmake --install .
  - cd $CI_PROJECT_DIR
  ## Shared library
  - cp /usr/local/lib/libcpr.so* dist/bin-shared
  # DPP (shared, .so)
  # - git clone https://github.com/brainboxdotcc/DPP.git dpp-src --depth 1
  # - cp -r --preserve=all dpp-src/ dpp-src-cached/ || true
  # - rm -rf cpr-src
  # - git clone https://github.com/brainboxdotcc/DPP.git dpp-src --depth 1
  # -- cp -r --preserve=all dpp-src-cached/* dpp-src/ || true
  # - rm -rf dpp-src-cached || true
  # - cd dpp-src && mkdir -p build && cd build
  # - cmake .. -DBUILD_SHARED_LIBS=ON -DBUILD_VOICE_SUPPORT=OFF -DDPP_BUILD_TEST=OFF
  # - cmake --build . -j4
  # - make install
  # - cd $CI_PROJECT_DIR
  ## Shared library
  # - cp /usr/local/lib/libdpp.so* dist/bin-shared
  ## Log all library locations
  - find . /usr /lib /lib64 /usr/local/lib /usr/lib /usr/local -name libgmp.so*
  - find . /usr /lib /lib64 /usr/local/lib /usr/lib /usr/local -name libgmp.a*
  - find . /usr /lib /lib64 /usr/local/lib /usr/lib /usr/local -name libbncsutil.so*
  - find . /usr /lib /lib64 /usr/local/lib /usr/lib /usr/local -name libbncsutil.a*
  - find . /usr /lib /lib64 /usr/local/lib /usr/lib /usr/local -name libstorm.so*
  - find . /usr /lib /lib64 /usr/local/lib /usr/lib /usr/local -name libstorm.a*
  - find . /usr /lib /lib64 /usr/local/lib /usr/lib /usr/local -name libminiupnpc.so*
  - find . /usr /lib /lib64 /usr/local/lib /usr/lib /usr/local -name libminiupnpc.a*
  - find . /usr /lib /lib64 /usr/local/lib /usr/lib /usr/local -name libcpr.so*
  - find . /usr /lib /lib64 /usr/local/lib /usr/lib /usr/local -name libcpr.a*
  # - find . /usr /lib /lib64 /usr/local/lib /usr/lib /usr/local -name libdpp.so*
  # - find . /usr /lib /lib64 /usr/local/lib /usr/lib /usr/local -name libdpp.a*
  # Aura (all shared libraries)
  - cd $CI_PROJECT_DIR
  - export AURABUILD_CPR=1
  # This takes too long.
  - export AURABUILD_DPP=0
  # Not yet supported in Linux
  - export AURABUILD_MDNS=0
  - export AURABUILD_MINIUPNP=1
  # Not yet supported in Linux
  - export AURABUILD_PJASS=0
  - ccache -z
  - make WFLAGS="-Wall -Wextra" OFLAGS="-O1"
  - ccache -s
  - make install
  - unset AURABUILD_CPR
  - unset AURABUILD_DPP
  - unset AURABUILD_MDNS
  - unset AURABUILD_MINIUPNP
  - unset AURABUILD_PJASS
  ## on static build failures, the error is reported iff mv below fails
  - mv /usr/bin/aura dist/bin-shared
  - cd dist/bin-shared
  - chmod +x aura
  - chmod +x *.so
  - chmod +x *.so.*
  - export LD_LIBRARY_PATH=$PWD
  ## test setting AURA_HOME
  ### expects [AURA] copying config-example.ini to config.ini...
  ### exit 1: no inputs connected
  ###          initialization failure - please review your configuration file
  - export AURA_HOME=$CI_PROJECT_DIR
  - ./aura --verbose --no-bnet --game-version=27 --log-level=debug --test --exit || echo $?
  ## test --config
  ### expects directly reads config-example.ini
  ### exits 1: no inputs connected.
  ###          initialization failure - please review your configuration file
  - ./aura --verbose --no-bnet --game-version=27 --config=config-example.ini --exit || echo $?
  ## test --config --stdpaths
  ### exits 1: required config file not found [config-example.ini]
  ###          error loading configuration
  - ./aura --verbose --stdpaths --no-bnet --game-version=27 --config=config-example.ini --log-level=debug --exit || echo $?
  ## test --config --stdpaths matching home dir
  ### exits 1: using $AURA_HOME=/builds/USER/aura-bot/
  ###          no inputs connected
  ###          initialization failure - please review your configuration file
  - ./aura --verbose --stdpaths --no-bnet --game-version=27 --config=../../config-example.ini --log-level=debug --exit || echo $?
  - export AURA_HOME=$PWD
  ## test running without config file
  ### exits 1: config.ini, config-example.ini not found within home dir
  ###          initialization failure - please review your configuration file
  - ./aura --verbose --no-bnet --game-version=27 --log-level=debug --exit || echo $?
  ## test running without config file
  ### exits 1: required config file not found [config-example.ini]
  ###          error loading configuration
  - ./aura --verbose --stdpaths --no-bnet --game-version=27 --config=config-example.ini --log-level=debug --exit || echo $?
  ## test hosting games (stdpaths, does not exist)
  ### exits 0: Input does not refer to a valid file
  ###          shutting down
  - ./aura --verbose --stdpaths --homedir=$CI_PROJECT_DIR --no-bnet --game-version=27 --auto-port-forward --check-joinable --lobby-timeout=1 --log-level=debug "wormwar.ini" || echo $?
  ## test hosting games (file, expect OK)
  ## exits 0: lobby time limit exceeded
  - ./aura --verbose --homedir=$CI_PROJECT_DIR --no-bnet --game-version=27 --auto-port-forward --check-joinable --lobby-timeout=1 --log-level=debug "wormwar.ini" || echo $?
  ## test hosting games (relative, expect OK)
  ## exits 0: lobby time limit exceeded
  - ./aura --verbose --homedir=$CI_PROJECT_DIR --no-bnet --game-version=27 --auto-port-forward --check-joinable --lobby-timeout=1 --log-level=debug "../../mapcfgs/wormwar.ini" || echo $?
  ## test hosting games (relative, expect OK)
  ## exits 0: lobby time limit exceeded
  - ./aura --verbose --stdpaths --homedir=$CI_PROJECT_DIR --no-bnet --game-version=27 --auto-port-forward --check-joinable --lobby-timeout=1 --log-level=debug "../../mapcfgs/wormwar.ini" || echo $?
  - unset AURA_HOME
  - unset LD_LIBRARY_PATH
