map.cfg.schema_number = 5

#####################################################################################
### Map Name Section:                                                             ###
### Only change the map filename for map.path and map.localpath                   ###
### then ensure the same map that you list here is wherever your maps folder is   ###
### (bot.maps_path in config.ini, usually the maps\ folder in the Aura folder)    ###
### Examples:                                                                     ###
### map.path = Maps\Download\Dota AllStars 6.59d.w3x                              ###
### map.localpath = Dota AllStars 6.59d.w3x                                       ###
#####################################################################################

# the map path tells Warcraft III clients where to find the map on their system
# it is NOT the path to the map on the Aura system, in fact Aura doesn't require the map at all
# this path should NOT start with a slash

map.path = Maps\FrozenThrone\Scenario\(12)WormWar.w3x

# the locale used to load the map

map.locale.lang_id = 0

# map local path (for map downloads and automatic map value calculation)
#  Aura doesn't require map files but if it has access to them it can send them to players
#  it can also automatically calculate map values such as map.size, map.info, map.crc, map.sha1, etc...
#  Aura will search bot.maps_path + map.localpath for the map file (bot.maps_path is set in the main config file)

map.local_path = (12)WormWar.w3x

# map title

map.title = Worm War

# map author

map.meta.author = Blizzard Entertainment

# map description

map.meta.desc = Every baby worm dreams of being a gladiator in the worm arena, where burly worms battle it out to eat sheep, grow, and squish their adversaries.

#####################################################################################
### Map Preview Section:                                                          ###
#####################################################################################

map.preview.image.mime_type = image/tga
map.preview.image.path = war3mapPreview.tga
map.preview.image.path_type = mpq
map.preview.image.size = 196652

#####################################################################################
### Manually entered information (when Aura cannot generate values properly)      ###
### Unless the map isn't working properly you probably don't have to change these ###
#####################################################################################

# map type
# this is only for stats tracking, set it to map.type = dota if it is a dota map

map.type =

# map players and teams

map.num_players = 12
map.num_teams = 12

#
# slot structure
#  [PID] [Download Status] [Slot Status] [Computer] [Team] [Colour] [Race] [Skill] [Handicap]
#  - PID is always 0
#  - Download Status is always 255
#  - Slot Status is 0 for open, 1 for closed, 2 for occupied
#  - Computer is 0 for no, 1 for yes
#  - Team
#  - Colour
#  - Race is 1 for human, 2 for orc, 4 for night elf, 8 for undead, 32 for random (add 64 to any of these for selectable)
#  - Skill is 0 for easy computer, 1 for normal computer or human, 2 for hard computer
#  - Handicap is 50/60/70/80/90/100
#

map.slot_1 = 0 255 0 0 0 0 96 1 100
map.slot_2 = 0 255 0 0 1 1 96 1 100
map.slot_3 = 0 255 0 0 2 2 96 1 100
map.slot_4 = 0 255 0 0 3 3 96 1 100
map.slot_5 = 0 255 0 0 4 4 96 1 100
map.slot_6 = 0 255 0 0 5 5 96 1 100
map.slot_7 = 0 255 0 0 6 6 96 1 100
map.slot_8 = 0 255 0 0 7 7 96 1 100
map.slot_9 = 0 255 0 0 8 8 96 1 100
map.slot_10 = 0 255 0 0 9 9 96 1 100
map.slot_11 = 0 255 0 0 10 10 96 1 100
map.slot_12 = 0 255 0 0 11 11 96 1 100

# map options
#  - you can combine these options by adding together all the options you want to use
#  - for example to have fixed player settings and custom forces you would use "96"
#  4 = melee
#  32 = fixed player settings
#  64 = custom forces

map.options = 0

# map dimensions

map.width = 84 0
map.height = 84 0

# map information (if incorrect it will force downloading for players and kick from the game lobby)

map.size = 382409
map.file_hash.crc32 = 80 219 105 206
map.file_hash.sha1 = 192 169 92 42 156 106 91 180 212 203 211 22 165 227 143 45 163 171 123 69
map.scripts_hash.blizz.v1.24 = 15 15 71 22
map.scripts_hash.sha1.v1.24 = 91 92 122 144 89 127 250 70 133 235 247 76 193 31 109 105 36 250 36 16

#####################################################################################
###    Values that are necessary to have, but rarely are required to be changed   ###
#####################################################################################

# map speed
#  slow, normal, fast

map.speed = fast

# map visibility
#  hide_terrain, explored, always_visible, default

map.visibility = default

# map observers
#  none, on_defeat, full, referees

map.observers = none

# map flags
#  - you can combine these flags by adding together all the options you want to use
#  - for example to have teams togethe and fixed teams, you would use 3
#  - to have teams together, fixed teams, and random races, you would use 19
#  1 = teams together
#  2 = fixed teams
#  4 = unit share
#  8 = random hero
#  16 = random races

map.flags = 19

# map filters are only used for filtering maps on battle.net and for specifying some metadata about the map
# most of these values won't affect anything important and can be changed as you wish

# map filter (maker)
#  - you can combine these flags by adding together all the options you want to use (some combinations may not make sense)
#  1 = map was made by user
#  2 = map was made by blizzard

map.filter_maker = 2

# map filter (type)
#  - you can combine these flags by adding together all the options you want to use (some combinations may not make sense)
#  1 = melee map
#  2 = scenario map (default)

map.filter_type = 2

# map filter (size)
#  - you can combine these flags by adding together all the options you want to use (some combinations may not make sense)
#  1 = small map
#  2 = medium map
#  4 = large map

map.filter_size = 4

# map filter (observers)
#  - you can combine these flags by adding together all the options you want to use (some combinations may not make sense)
#  1 = full observers
#  2 = observers on death
#  4 = no observers

map.filter_obs = 4

# editor version
map.editor_version = 6052

# requires TFT
map.expansion = yes

# min game version required
map.game_version.min = 1.19

# min game version suggested
map.game_version.suggested.min = 1.19

# disable FFA name obfuscation
map.hosting.nicknames.hide_in_game = never

# improved default latency for WormWar
map.hosting.latency.default = 30
map.net.sync.start_lag.players.default_ms = 2880
map.net.sync.stop_lag.players.default_ms = 720

# showcase ping equalizer
map.hosting.latency.equalizer.enabled = yes
map.hosting.latency.equalizer.max_delay = 450
